In [4]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [5]:
ls = [1,2,3,4,5,6,7]

In [6]:
print(ls)


[1, 2, 3, 4, 5, 6, 7]


In [7]:
arr = np.array(ls)

In [8]:
print(arr)


[1 2 3 4 5 6 7]


In [11]:
np.random.randint(0,10)

4

In [12]:
np.random.randint(0,10)

2

In [14]:
lis = np.random.randint(0,10,size=5)
print(lis)

[9 8 7 3 2]


In [19]:
new = np.random.randint(0,100,(3,4,5))
print(new)

[[[18 74 94 43 89]
  [32 19 72 28 66]
  [94 73 54 85 26]
  [91 78 15 30  1]]

 [[98 35 69 15 36]
  [22 60 68 23 31]
  [31 54 31 70 96]
  [67 87  8 78 35]]

 [[ 4  2 10 10 53]
  [17 67  2 49 50]
  [15 68 55 39 64]
  [36 90  5 70 52]]]


In [1]:
import numpy as np 

In [3]:
arr = np.arange(0,10)

In [7]:
print(arr)

[0 2 4 6 8]


In [2]:
import numpy as np
arr = np.arange(0,5)

In [5]:
arr1 = np.arange(6,11)
arrsum = arr + arr1 
print(arrsum)

[ 6  8 10 12 14]


In [7]:
arr + 100 

array([100, 101, 102, 103, 104])